version: "3"
services:
  app: 
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db
    links:
      - db
    restart: always
    networks:
      - master-network
  db:
    container_name: local-db
    build: infra/postgres/.
    environment:
      POSTGRES_DB: test-db
    #   POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: test
      POSTGRES_PASSWORD: testtset
    ports:
      - 5432:5432
    networks:
      - master-network
  redis:
    image: redis
    ports:
      - 6379:6379
networks:
  master-network:
    name: test-network