version: "3"
services:
  db:
    build: infra/postgres/.
    environment:
      POSTGRES_DB: test-db
    #   POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: test
      POSTGRES_PASSWORD: testtset
    ports:
      - 5432:5432
  redis:
    image: redis
    ports:
      - 6379:6379
